# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'

steps:
- script: |
    cd linux && docker build -t "usd-docker/vfx-lite:2018-centos7" -f centos7/vfx-lite-2018/Dockerfile . 
    docker tag "usd-docker/vfx-lite:2018-centos7" "usd-docker/vfx-lite:latest-centos7"
    docker tag "usd-docker/vfx-lite:2018-centos7" "aloysbaillet/vfx-lite:latest-centos7"
  displayName: 'docker build vfx-lite'
- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(dockerId)/vfx-lite
  displayName: 'docker push vfx-lite'
