############################################################
# Dockerfile to install maya2016's QT4

FROM usd-docker/maya2016:centos6-usd-0.7

LABEL maya2016.qt4.version="1" maintainer="Animal Logic"

COPY scripts/build_maya2016_qt4_devkit.sh /tmp/

RUN /tmp/build_maya2016_qt4_devkit.sh
