############################################################
# Dockerfile to install maya2016
# Based on nvidia/base:centos6-usd-0.7

FROM usd-docker/vfx:latest-centos6

LABEL maya.version="2016.1" maintainer="Animal Logic"


# Setup environment
# Workaround for "Segmentation fault (core dumped)"
# See https://forums.autodesk.com/t5/maya-general/render-crash-on-linux/m-p/5608552/highlight/true
ENV MAYA_LOCATION=/usr/autodesk/maya

COPY scripts/build_maya2016.sh /tmp/

# Make mayapy the default Python
RUN /tmp/build_maya2016.sh \
    && echo alias hpython="\"$MAYA_LOCATION/bin/mayapy\"" >> ~/.bashrc \
    && echo alias hpip="\"mayapy -m pip\"" >> ~/.bashrc 

ENV PATH=$MAYA_LOCATION/bin:$PATH \
    MAYA_DISABLE_CIP=1
