############################################################
# Dockerfile to install maya2016
# Based on nvidia/base:centos6-usd-0.7

FROM usd-docker/vfx:centos6-usd-0.7

MAINTAINER Animal Logic

ENV MAYA_LOCATION=/usr/autodesk/maya

COPY scripts/build_maya2016.sh /tmp/
RUN /tmp/build_maya2016.sh

# Make mayapy the default Python
RUN echo alias hpython="\"$MAYA_LOCATION/bin/mayapy\"" >> ~/.bashrc && \
    echo alias hpip="\"mayapy -m pip\"" >> ~/.bashrc

# Setup environment
ENV PATH=$MAYA_LOCATION/bin:$PATH

# Workaround for "Segmentation fault (core dumped)"
# See https://forums.autodesk.com/t5/maya-general/render-crash-on-linux/m-p/5608552/highlight/true
ENV MAYA_DISABLE_CIP=1

#Using Maya's OpenColorIO causes runtime linker errors on the getProcessor method when using mayapy
#Move their OpenColorIO to the side.
CMD mv $MAYA_LOCATION/lib/libOpenColorIO.so.1.0.9 $MAYA_LOCATION/lib/libOpenColorIO.so.1.0.9_BACKUP
CMD mv $MAYA_LOCATION/lib/libOpenColorIO.so.1 $MAYA_LOCATION/lib/libOpenColorIO.so.1_BACKUP

# Cleanup
CMD bash