############################################################
# Dockerfile to build USD on VFX Platform 2016
# Based on nvidia/cuda:devel-centos6

FROM usd-docker/maya2018:latest-centos6

ENV USD_VERSION "0.8.1"
LABEL pxr.usd.version="${USD_VERSION}" maintainer="Aloys.Baillet - Animal Logic"
COPY scripts/build_usd.sh /tmp/
RUN /tmp/build_usd.sh