############################################################
# Dockerfile to build USD Maya

FROM usd-docker/maya2018:latest-centos7

ENV USD_VERSION "18.09"
ENV MAYA_MAJOR_VERSION "2018"
LABEL pxr.usd.version="${USD_VERSION}" maintainer="Aloys.Baillet - Animal Logic"
COPY scripts/download_usd.sh scripts/build_usd.sh /tmp/
RUN /tmp/download_usd.sh && \
    /tmp/build_usd.sh

ENV USD_INSTALL_ROOT $BUILD_DIR/usd/$USD_VERSION
ENV USD_CONFIG_FILE $USD_INSTALL_ROOT/pxrConfig.cmake
ENV PATH $PATH:$USD_INSTALL_ROOT/bin
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$USD_INSTALL_ROOT/lib
ENV PYTHONPATH $PYTHONPATH:$USD_INSTALL_ROOT/lib/python
