############################################################
# Dockerfile to build USD Maya

FROM usd-docker/maya2017:latest-centos7

ENV USD_VERSION "0.8.0"
LABEL pxr.usd.version="${USD_VERSION}" maintainer="Aloys.Baillet - Animal Logic"
COPY scripts/build_usd.sh /tmp/
RUN /tmp/build_usd.sh
