############################################################
# Dockerfile to install maya2017
# Based on nvidia/base:centos7-usd-0.8

FROM usd-docker/vfx:latest-centos7

LABEL maya.version="2017.4" maintainer="Animal Logic"

ENV MAYA_INSTALL_LOCATION=$BUILD_DIR \
    MAYA_LOCATION=$MAYA_INSTALL_LOCATION/usr/autodesk/maya2017
ENV HTTP_HOSTNAME=_YOUR_HOST_IP_ADRESS_HERE_

COPY scripts/build_maya2017.sh /tmp/

RUN yum install -y tcsh libXp libXpm fam libpng12 libXcomposite libjpeg

RUN /tmp/build_maya2017.sh \
    && echo alias hpython="\"$MAYA_LOCATION/bin/mayapy\"" >> ~/.bashrc \
    && echo alias hpip="\"mayapy -m pip\"" >> ~/.bashrc

# Setup environment
# Workaround for "Segmentation fault (core dumped)"
# See https://forums.autodesk.com/t5/maya-general/render-crash-on-linux/m-p/5608552/highlight/true

ENV PATH=$MAYA_LOCATION/bin:$PATH \
    MAYA_DISABLE_CIP=1
