############################################################
# Dockerfile to install maya2018
# Based on nvidia/base:centos7-usd-0.8

FROM usd-docker/vfx:latest-centos7

LABEL maya.version="2018.0" maintainer="Animal Logic"

ARG current_host_ip_address

ENV MAYA_LOCATION=$BUILD_DIR/maya2018DevKit \
    HTTP_HOSTNAME=$current_host_ip_address \
    MAYA_EXECUTABLE=$MAYA_LOCATION/bin/maya \
    MAYA_MAJOR_VERSION="2018"

COPY scripts/build_maya2018.sh scripts/download_dcc.sh /tmp/

RUN /tmp/download_dcc.sh && \
    /tmp/build_maya2018.sh
