############################################################
# Dockerfile to install maya2018
# Based on nvidia/base:centos7-usd-0.7

FROM usd-docker/vfx:centos7-usd-0.7

MAINTAINER Animal Logic

ENV MAYA_FILENAME Maya_PR79_Linux_64bit.tgz
ENV MAYA_DOCKER_PATH  $DOWNLOADS_DIR/$MAYA_FILENAME

ENV MAYA_DEVKIT_FILENAME Maya_PR79_Linux_64bit_DEVKIT.tgz
ENV MAYA_DEVKIT_DOCKER_PATH $DOWNLOADS_DIR/$MAYA_DEVKIT_FILENAME

ENV MAYA_INSTALL_LOCATION $BUILD_DIR
ENV MAYA_LOCATION $MAYA_INSTALL_LOCATION/usr/autodesk/maya2018

COPY scripts/build_maya2018.sh /tmp/

COPY apps/$MAYA_FILENAME $MAYA_DOCKER_PATH
COPY apps/$MAYA_DEVKIT_FILENAME $MAYA_DEVKIT_DOCKER_PATH

COPY scripts/build_maya2018.sh /tmp/
RUN /tmp/build_maya2018.sh

# Make mayapy the default Python
RUN echo alias hpython="\"$MAYA_LOCATION/bin/mayapy\"" >> ~/.bashrc && \
    echo alias hpip="\"mayapy -m pip\"" >> ~/.bashrc

# Setup environment
ENV PATH=$MAYA_LOCATION/bin:$PATH

# Workaround for "Segmentation fault (core dumped)"
# See https://forums.autodesk.com/t5/maya-general/render-crash-on-linux/m-p/5608552/highlight/true
ENV MAYA_DISABLE_CIP=1

CMD bash
